### ISSUE TITLE
Bug: cannot auto import

### ISSUE THREAD

**Issue by tung-eh** [Galooshi/import-js#538] opened 2019-11-13 07:57 UTC
Importjs will not works whenever I used this kind of syntax for omitting array value
```
  const [, b] = [1, 2];
```

**Comment by mikabytes** [comment] 2024-01-27 09:55
Hmm, I could not reproduce this bug. For example if I have two files:

```
// b.js
const [, b] = [1, a];

// a.js
const a = 5;
export default a;
```

and then run

```
importjs fix b.js
```

Then it adds the line

```
import a from './a.js'
``` 

So I'll close this for now, but if this is still relevant for you then please reopen this issue with steps on how to reproduce. Thanks!

**Closed by mikabytes** 2024-01-27 09:55 UTC
