### ISSUE TITLE
Option to add leading prefix to imports

### ISSUE THREAD

**Issue by awatson1978** [Galooshi/import-js#288] opened 2016-06-26 14:58 UTC
Hi there,
First of all, let me just say that this package is such a relief.  Thank you, thank you for putting this together.  I've been in import hell as I get up to speed with imports, and having this package is such a relief already.

So, feature request.

When using Meteor, everything is working swimmingly, but we need an option for a leading prefix.  For instance, I press ``Cmd+Shift+j`` over the word "AddPost", and we get the following situation:

```js
// created import string 
import AddPost from 'imports/ui/workflows/posts/AddPost';

// desired import string 
import AddPost from '/imports/ui/workflows/posts/AddPost';
```

Apparently Meteor want's absolute URLs that begin with a `/`.

Would you be willing to accept a PR for this?

**Comment by trotzig** [comment] 2016-06-26 19:03
Hi @awatson1978, and thanks for the kind words!

Just to better understand your situation, the leading slash isn't referring to the root of the file system, right? It's a way in Meteor to refer to the root of the app, correct? 

We're definitely open to a PR for this. I think you could hook into [the `toImportStatement` method of the `JsModule` class](https://github.com/Galooshi/import-js/blob/fe7519078dfab6ee3751d2e274c111c4508a8fa3/lib/JsModule.js#L169). That would make all import paths subject to the transformation, which I think is good. 

How would you feel about naming the configuration option `importPathPrefix`? 

You should also be aware that we are considering allowing the `.importjs.json` config file to also be pure javascript (`.importjs.js`). When we do that, we would probably solve this use-case by allowing people to configure a `prepareImportPath` method. But that's part of the long-term plan for import-js, and not something that we'll look into any time soon.

**Comment by trotzig** [comment] 2016-06-26 19:06
Oh, and I should probably ask before you go down the path of preparing the PR: would relative paths work? I'm looking at a few Meteor examples and it looks like they're using relative paths there. https://www.meteor.com/tutorials/react/components

```js
import AddPost from '../posts/AddPost';
```

**Comment by awatson1978** [comment] 2016-06-26 19:30
Hi @trotzig,
So, I'm not a core developer on Meteor, although I do maintain a distro for healthcare users. 

As I understand things, the leading slash refers to the root of the _app_.  However, I wouldn't completely rule out the possibility that there's a temp directory somewhere.  The Meteor tool is a pipeline build tool; so it actually compiles into Node code.  Slight chance there's a temp directory involved.  But otherwise, lets just assume that it's the root of the app.   

As for the relative paths, that's exactly what we're trying to move away from.  As a distro maintainer, I cater to a different user base than the core team.  The core team is a bit more focused on bleeding edge development; whereas the clinical track is a bit more focused on long-term stable (LTS) releases.  

The imports are relatively new (less than 4 months old?); and while the early adopters were comfortable using relative paths, the clinicians and devs I work with are going to have a bit harder time with them.  After migrating one of our larger apps over, it's starting to look like we're taking a position that the style guides should be updated to use absolute paths (similar to C# and Java).  At least, we're going to use it in the Clinical Meteor styleguide documentation.

Also, we've been experimenting with ``import-js`` precisely because of it's ability to specify ``"useRelativePaths": false``.   :)

**Comment by rhettlivingston** [comment] 2016-07-13 20:56
@awatson1978, are you working a PR for this? If not, I could do so.

Things have already changed since the above discussion. The important aspects are that @trotzig has added support for js configuration files in response to our needs and there is now a "meteor" environment that is implemented in lib/environments/meteorEnvironment.js. This environment is actually just a js configuration file that gets merged with the configuration specified in .importjs.js(on) when `environments: ["meteor"]` is encountered in the user's configuration. So the option mentioned in trotzig's first comment above is now a possibility.

**Comment by awatson1978** [comment] 2016-07-14 11:27
Unfortunately, not actively.  I was asked to present at the United Nations this past weekend, which has taken up all my time for the past few weeks.  If you have a quick-and-easy solution, I'd say go for it. And a big THANK YOU!  :)

**Comment by trotzig** [comment] 2016-07-14 11:40
Hey @awatson1978, where are your priorities!? Surely presenting at the UN can't be more important than adding a feature to ImportJS.

Just kidding -- that's amazing!

**Comment by rhettlivingston** [comment] 2016-07-14 14:59
I agree! Consider it handled!

**Comment by trotzig** [comment] 2016-07-14 18:39
I've started looking into this, and I'm currently considering two options:
A) Add an `importPathPrefix` configuration option that if resolved to a string will be used as a prefix when constructing the import path. 
B) Add an `importPathModifier` (name?) which is a configuration function that you can implement to modify the import path. 

A is simpler, but only solves our specific use-case. B is more general, but is easier to "abuse" or somehow misunderstand. I'm interested to hear other people's thoughts on this. And perhaps we can come up with a better name for B.

**Comment by trotzig** [comment] 2016-07-14 18:41
`importPathModifier` would look something like this:

```
importPathModifier: ({ pathToImportedModule }) {
  if (isMeteorPath(pathToImportedModule)) {
    return '/' + pathToImportedModule;
  }
  return pathToImportedModule;
});
```

**Comment by rhettlivingston** [comment] 2016-07-14 18:53
The names have been bugging me because I don't see A as having the potential to be applicable to all import paths, only absolute ones.

I'm thinking Option B might be really cool with a little more information - the path to the module doing the importing. If we expose this to the user at some point, that could allow projects to choose mixed implementations such as always using an absolute path if referencing anything that involves traversing up the tree and a relative path to all other modules.

As to the name, maybe its an importPathGenerator?

**Comment by lencioni** [comment] 2016-07-14 19:21
I also like option B, since its implementation should be pretty straightforward. Perhaps the name could just be as simple as `importPath`?

**Comment by trotzig** [comment] 2016-07-14 19:30
We already pass in `pathToCurrentFile`. Is that enough to support what you're thinking of @rhettlivingston ? See https://github.com/Galooshi/import-js#dynamic-configuration

**Comment by rhettlivingston** [comment] 2016-07-14 20:00
> We already pass in pathToCurrentFile. Is that enough to support what you're thinking of
Yep. Brain slip.

Another thought... actually weaker than that... feeling perhaps... on naming. Your use of "aliases" in your existing options threw me a little as a new user because the [MDN javascript reference for import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) used the word "alias" in the context of imports.
```js
import { member as alias } from "module-name";
```
So, my first thought was that you were giving a means for us to map our preferred local names back to the real ones. Of course, that isn't a great practice in general, though sometimes a necessary one to fix a namespace clash.

My point is that I've not seen the module-name referred to as an "import path" elsewhere. It is a "module-name" in the above widely used reference and a "ModuleSpecifier" in the [ES7 specification](https://tc39.github.io/ecma262/#sec-imports). It may be better practice to choose a standard reference and utilize it in our language.

**Comment by trotzig** [comment] 2016-07-14 20:56
It's really useful to get that type of feedback. I'll try to look over naming at some point. I think we already have a system in place to rename an option while still keeping support for a deprecated old name. 

Maybe `shortCuts` would work instead of `aliases`? And how about `pathToModule` for this new option? I feel like "path" should be part of it, because in most cases we are dealing with paths. Even with package dependencies, we can think of the the string as a path within the node_modules folder.

**Comment by lencioni** [comment] 2016-07-14 21:13
I think matching the language of the spec makes sense.

**Comment by rhettlivingston** [comment] 2016-07-14 21:37
>  I feel like "path" should be part of it, because in most cases we are dealing with paths

I can buy that, either pathToModule or moduleSpecifier sounds good to me. They at least both have "module".

> Maybe shortCuts would work instead of aliases

I don't have a lot of opinion on the right name for this because its purpose is a bit odd to me. I'm guessing it was made available prior to namedExports and evolves from the thought that most unresolved variables should resolve to the default export of some module with the same name. It might have been your first handling of the fact that that thought is limited. In Meteor code, that thought appears to break down more often than not. We don't seem to have a lot of default exporting going on.

I don't think I'd ever use your "aliases" option except perhaps in the case of the .scss example. I've already mentioned in the past that I'm using namedExports to accomplish what is shown in your aliases example.
```js
  namedExports: {
    'meteor/jquery': ['$', 'jQuery'],
    'meteor/underscore': ['_'],
  }
```
Also, if we get to the point of being able to scan packages for their exports, I think the need for "aliases" disappears altogether.

**Comment by trotzig** [comment] 2016-07-15 05:00
Yeah, with scanning the need for aliases becomes less important at least. Just for some more context, here's what the aliases configuration looks like for the app that powers brigade.com:

```json
  "aliases": {
    "$": "jquery",
    "branch": "imports?define=>false!branch-sdk",
    "PureRenderMixin": "react-addons-pure-render-mixin",
    "Raven": "raven-js",
    "Uri": "urijs",
    "styles": "./index.scss",
    "PieChart": "react-simple-pie-chart",
    "Route": "react-router/lib/Route",
    "IndexRoute": "react-router/lib/IndexRoute",
    "Redirect": "react-router/lib/Redirect"
  },
```

Some of these are just so that we can use a more convenient name for the variable (instead of the package name). E.g. `$`. We also used to have `_` for underscore.js here, but moved it to named exports instead. 

The `branch` one is interesting because we need to import it using a special loader (this is an app bundled by webpack, and this is one way to specify that a special loader is to be used). When we have the ability to modify the module specification/path we don't need this as an alias (#288). 

Some of them can probably be removed and replaced by a few prefixes added to [`ignorePackagePrefixes`](https://github.com/Galooshi/import-js#ignorepackageprefixes). E.g. `PieChart`. 

The react-router could be removed if the package specified these as being exported. This is further discussed in #107.

Raven and Uri are probably a symptom that we should ignore the `/[-.]?js/` part of a package. I added an issue for that: #309.

**Comment by lencioni** [comment] 2016-07-15 15:26
These are the aliases we have right now:

```js
"aliases": {
  "$": "jquery",
  "_": "underscore",
  "copy": "copy-to-clipboard",
  "cx": "classnames",
  "wrap": "mocha-wrap",
  "sinon": "sinon-sandbox"
},
```

**Comment by rhettlivingston** [comment] 2016-07-15 16:10
My apologies. It has clicked with me. You are actually using 'aliases' correctly. It's just implementing what a minimal case of the alias and lacking support for the more generalized ES6 aliases.
```json
"aliases": {
  "copy": "copy-to-clipboard"
}
```
results in
```js
import copy from 'copy-to-clipboard';
```
Because the default export in ES6 is actually just an export with the name 'default', that is an exactly equivalent shorthand for the more generalized
```js
import { default as copy } from 'copy-to-clipboard';
```

And these particular cases can't be automated by scanning of the js files. In the case of "copy-to-clipboard", the export statement within it's index.js is
```js
module.exports = copy;
```
So, "copy" is there, but there is no syntactic guarantee that it will be. Grabbing it as an alias would just be a guess.

The real thing guiding people to use "copy" as the alias for that default export is the package's README.

Instead of renaming this, we should be considering how it could be generalized in the future. The problem is, it is currently implying something that needs to be explicit in the general case. The above case states "copy" is the alias for the "default" export of "copy-to-clipboard". We need a means of specifying which export the alias is for.

**Comment by rhettlivingston** [comment] 2016-07-25 00:05
The changes in #310 Module Specifier and #313 Fix Meteor absolute path references to modules resolved this issue.

Closing #288.

**Closed by rhettlivingston** 2016-07-25 00:05 UTC
