### ISSUE TITLE
Support for jsconfig.json

### ISSUE THREAD

**Issue by mnieber** [Galooshi/import-js#556] opened 2020-06-03 14:03 UTC
When I create an application with "create react app" then it places all source under the /src directory. In that case, imports do not have a "src/" prefix. However, importjs will produce import paths that *do* have the "src/" prefix. Is it possible to fix this? Or am I doing something wrong?

I thought that one option could be to take the value of `compilerOptions.baseUrl` in the `jsconfig.json` file into account when determining the import paths.

**Comment by coagmano** [comment] 2020-06-11 02:29
I've gotten around it by putting the `package.json` and `node_modules` in `/src`, which doesn't work for create react app...

Should be relatively easy to add to here:
https://github.com/Galooshi/import-js/blob/master/lib/findProjectRoot.js

If you wanted to start a proposal

**Comment by trotzig** [comment] 2020-06-11 10:37
@mnieber Could you give a more specific example? What's the location of the file you're importing into and what's the location of the file/module you're importing? What did you expect import statements to look like vs what do they end up looking like? 

Depending on the scenario here, you could look into using https://github.com/Galooshi/import-js#importstatementformatter.

**Comment by mnieber** [comment] 2020-06-12 20:38
I've found a solution based on an undocumented feature: the `.importjs-root` file. Just like `package.json` this file indicates the root directory for import paths found by importjs. By placing both `.importjs-root` and `.importjs.js` in the `src` directory, I managed to get import paths that do not start with the `src/` prefix.
Maybe it's worth documenting `.importjs-root`?

**Comment by mnieber** [comment] 2020-06-14 22:31
Unfortunately, my solution (described above) is not adequate because now `node_modules` is no longer considered.

**Comment by mikabytes** [comment] 2024-01-27 09:43
I couldn't reproduce this issue. Perhaps it's been solved?

Here's what I did:

```
mkdir /tmp/test ; cd /tmp/test
npx create-react-app .
echo "export default 'hello'" > src/b.js
echo "console.log(b)" >> src/App.js
importjs fix src/App.js
```

ImportJS then went ahead and added this line:

```
import b from "./b.js";
```

Notice that it did not include the `src` in the path.

I'll go ahead and close this now as I can't reproduce the issue. However, if you feel I missed something then please go ahead and reopen it and describe how to reproduce step-by-step. Thanks!

**Closed by mikabytes** 2024-01-27 09:43 UTC
